version: '3'
services:
  postgres-dev:
    image: postgres:10
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mbq_dev_user
      - POSTGRES_PASSWORD=mFl4g5Bx~40|C1w
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  api:
    build: ./backend/
    container_name: crypto_api
    working_dir: "/code"
    volumes:
      - ./backend:/code
    command: "npx pm2 start ecosystem.config.js --no-daemon"
    ports:
      - 3000
    labels:
      - traefik.frontend.rule=PathPrefix:/api/
      - traefik.backend=api
      - traefik.port=3000
      - traefik.enable=true

    depends_on:
      - postgres-dev

  server:
    image: traefik
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      # - 443:443
      - 8080:8080
    depends_on: 
      - api