version: '3'
services:
  postgres-dev:
    image: postgres:11
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=crypto_store
    ports:
      - 5432:5432

  api:
    build: .
    container_name: crypto_api
    working_dir: "/code"
    volumes:
      - .:/code
    command: "npx pm2 start ecosystem.config.js --no-daemon"
    ports:
      - 4000
    labels:
      - traefik.frontend.rule=PathPrefix:/
      - traefik.backend=api
      - traefik.port=4000
      - traefik.enable=true

    depends_on:
      - postgres-dev

  server:
    image: traefik:1.7
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on: 
      - api