FROM node:8.10
RUN mkdir /code
WORKDIR /code
COPY package.json .
COPY ecosystem.config.js .
RUN npm install -g pm2
# Show current folder structure in logs
# RUN ls -al -R
RUN npm install
COPY . .
ENV NPM_CONFIG_LOGLEVEL warn


